component: scf
name: ap-guangzhou_webfunc_helloworld
inputs:
  name: helloworld
  src:
    src: ./src
  type: web
  runtime: Nodejs14.18
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE