component: scf
name: ap-shanghai_doze_demo_py310
inputs:
  name: coze_demo_py310
  src:
    src: ./src
  type: web
  runtime: Python3.10
  namespace: default
  region: ap-shanghai
  memorySize: 512
  timeout: 60
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE