component: website
name: websiteInstance
app: websiteAppName
stage: dev

inputs:
  src:
    src: ./src
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: my-bucket
  protocol: http
  replace: false
  disableErrorStatus: false
  autoSetupAcl: true
  autoSetupPolicy: false
  cors:
    - allowedOrigins:
        - '*.tencent.com'
        - '*.qcloud.com'
      allowedMethods:
        - PUT
        - POST
        - DELETE
        - HEAD
      allowedHeaders: '*'
      maxAgeSeconds: 0