component: scf
name: ap-guangzhou_default_SendEmailByCMQ
inputs:
  name: SendEmailByCMQ
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
    - type: cmq
      enable: true
