component: scf
name: ap-guangzhou_default_webscoket_transport_fun
org: app
app: webscoket_transport_fun
stage: dev
inputs:
  name: webscoket_transport_fun
  src: ./
  description: >-
    本示例基于 API
    网关实现websocket功能，API网关和云函数一起构成websocket的Server端，由API网关承载和Client端的长连接。websocket一共需要3类函数承载，分别是注册函数、传输函数和清理函数，本函数为传输函数。
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
