component: scf
name: ap-guangzhou_default_API_GW_Html_Demo
org: app
app: API_GW_Html_Demo
stage: dev
inputs:
  name: API_GW_Html_Demo
  src: ./
  description: >-
    This demo is mainly to show how to return custom html in serverless.
    本示例主要演示如何配置 API 网关触发器返回自定义的html页面
  handler: index.main_handler
  runtime: Nodejs10.15
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  events:
     - apigw: # api网关触发器
        name: serverless
        serviceId: # input API gateway serviceId
        parameters:
          protocols:
            - http
          description: the serverless service
          environment: release
          endpoints:
            - path: /
              method: GET
              function:
                isIntegratedResponse: TRUE
