component: scf
name: ap-shanghai_webfunc_langgraph
inputs:
  name: langgraph
  src:
    src: ./src
  type: web
  runtime: Nodejs20.19
  namespace: default
  region: ap-shanghai
  memorySize: 512
  timeout: 60
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE