component: scf
name: ap-guangzhou_flask_demo
inputs:
  name: flask_demo
  src:
    src: ./src
  type: web
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
      environment: release
      netTypes:
        - OUTER
      apis:
        - path: /
          method: ANY