component: scf
name: ap-guangzhou_default_SendEmail_By_CMQ
org: app
app: SendEmail_By_CMQ
stage: dev
inputs:
  name: SendEmail_By_CMQ
  src: ./
  description: 本示例通过接收 CMQ 消息队列中指定格式的消息，并根据消息内容向指定的邮箱发送邮件
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  events:
    - cmq: # CMQ Topic 触发器
       name: # input CMQ trigger  name //e.g. test
       parameters:
          name: # input CMQ Topic name //e.g. topicxxx
          enable: true
