component: scf
name: ap-guangzhou_default_helloworld
inputs:
  name: helloworld
  src:
    src: ./src
  handler: index.main_handler
  runtime: Php8.0
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
