app: appDemo
stage: dev
component: zblogphp
name: zblogphpDemo

inputs:
  region: ap-beijing
  zone: ap-beijing-3
  # src:
    # # 指定 zblogphp 源码目录
    # src: ./test/ # 本地需要打包的文件目录
    # exclude: # 被排除的文件或目录
    #   - .env