component: scf
name: ap-guangzhou_default_Word_Recognition
org: app
app: Word_Recognition
stage: dev
inputs:
  name: Word_Recognition
  src: ./
  description: >-
    This demo uses API GW trigger and SCF to build WEB backend service.It can
    realize word recognition from picture. 本示例使用 API
    网关触发器和云函数快速构建web后台，实现图片中文字识别的功能，用户通过 API
    网关上传图片文件，上传后的文件会保存在COS，并调用AI接口实现文字识别，把结果返回前端
  handler: Word_Recognition.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 10
  events:
     - apigw: # api网关触发器
        name: serverless
        serviceId: # input API gateway serviceId
        parameters:
          protocols:
            - http
          description: the serverless service
          environment: release
          endpoints:
            - path: /
              method: GET
              function:
                isIntegratedResponse: TRUE

