component: scf
name: ap-guangzhou_default_CLSToElasticsearch
inputs:
  name: CLSToElasticsearch
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 30
