component: scf
name: ap-guangzhou_default_COSCdnRefresh
inputs:
  src:
    src: ./src
  handler: index.main_handler
  memorySize: 128
  name: COSCdnRefresh
  region: ap-guangzhou
  runtime: Nodejs12.16
  asyncRunEnable: TRUE
  traceEnable: TRUE
  timeout: 86400
