component: scf
name: ap-guangzhou_egg_demo
inputs:
  name: egg_demo
  src:
    src: ./src
  type: web
  runtime: Nodejs12.16
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
      environment: release
      netTypes:
        - OUTER
      apis:
        - path: /
          method: ANY
