component: scf
name: ap-guangzhou_default_Get_COS_Object
org: app
app: Get_COS_Object
stage: dev
inputs:
  name: Get_COS_Object
  src: ./
  description: 本示例配置了 COS 触发器，当有文件上传到对应的 COS bucket时，会触发云函数执行，并把文件下载到本地临时目录，用做后续处理
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  events:
     - cos: # cos触发器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true


