component: scf
name: ap-guangzhou_default_GetValueCreateQRcodeAPIGWDemo
inputs:
  name: GetValueCreateQRcodeAPIGWDemo
  src:
    src: ./src
  description: >-
    This demo is mainly to show how to use resources, how to get values from the
    web users, and how to return a web or a file.
    本示例主要展示在SCF中对各种资源的引用方法，包括include
    php文件、调用上传到SCF中的非php文件、使用/tmp临时目录，同时展示了SCF中3种获取用户提交数据的方法，最后演示如何返回一个网页或文件。
  handler: index.main_handler
  runtime: Php7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 10
  triggers:
    - type: apigw
      protocols:
        - http
      environment: release
      apis:
        - path: /
          method: GET
          function:
            isIntegratedResponse: true
